version: '3.8'

services:
  catalogo-app:
    build: .
    container_name: catalogo-app-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalogo-db:5433/catalogo_db
      SPRING_DATASOURCE_USERNAME: user_catalogo
      SPRING_DATASOURCE_PASSWORD: pass_catalogo
    depends_on:
      - catalogo-db

  catalogo-db:
    image: postgres:13-alpine
    container_name: catalogo-db-container
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: catalogo_db
      POSTGRES_USER: user_catalogo
      POSTGRES_PASSWORD: pass_catalogo
    volumes:
      - catalogo-data:/var/lib/postgresql/data

volumes:
 catalogo-data:
