# ===============================
# Configuración de aplicación
# ===============================
server.port=8080
spring.application.name=catalogo-service

# ===============================
# Configuración de Base de Datos (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://catalogo-db:5432/catalogo_db
spring.datasource.username=user_catalogo
spring.datasource.password=pass_catalogo
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# Variables custom de la app
# ===============================
app.rabbitmq.exchange=peliculas.exchange
app.rabbitmq.queue=peliculas.queue
app.rabbitmq.routingkey=pelicula.creada


